// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
import core/types::{Addr}
import sys/libc::*

pub fn sys_clock_monotonic(ts_addr: Addr) -> bool {
    // CLOCK_MONOTONIC (6) on macOS
    unsafe { return libc_clock_gettime(6, ts_addr) == 0 }
}

pub fn sys_clock_realtime(ts_addr: Addr) -> bool {
    // CLOCK_REALTIME (0) on macOS
    unsafe { return libc_clock_gettime(0, ts_addr) == 0 }
}
