#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import os

def main():
    json_path = "/home/zhyi/GitDP/tokalang/spec/diagnostic.map.json"
    def_path = "/home/zhyi/GitDP/tokalang/include/toka/DiagnosticDefs.def"

    if not os.path.exists(json_path):
        print(f"Error: {json_path} does not exist.")
        return

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    diagnostics = data.get("diagnostics", {})

    lines = []
    lines.append("// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.")
    lines.append("//")
    lines.append("// Licensed under the Apache License, Version 2.0 (the \"License\");")
    lines.append("//")
    lines.append("// include/toka/DiagnosticDefs.def")
    lines.append("// WARNING: This file is automatically generated from spec/diagnostic.map.json.")
    lines.append("// DO NOT EDIT THIS FILE MANUALLY! Any manual edits will be overwritten.")
    lines.append("")

    # We want to group or categorize them nicely or just output in insertion order
    # Let's categorize them by code prefix just to make the generated file beautiful and structured!
    categories = [
        ("Sema: Scope & Identifiers", lambda c: c in ["E0401", "E0462", "E0402", "E0403", "E0404", "E0405", "E0463", "N0003", "N0004", "E0406", "E0407", "N0001"]),
        ("Sema: Type Checking & Operations", lambda c: c in ["E0408", "E0469", "E0409", "E0410", "E0411", "E0412", "E0413", "E0414", "E0415", "E0459"]),
        ("Sema: Shape & Structs", lambda c: c in ["E0416", "E0417", "E0418", "E0419", "E0420", "E0421", "E0422", "E0423", "E0424", "E042A", "E042B", "E042C", "E042D", "E042E", "E0425", "E0426", "E0427", "N0002", "E0470", "E0471", "E0472"]),
        ("Sema: Traits & Interfaces", lambda c: c in ["E0428", "E0429", "E0430"]),
        ("Sema: Control Flow & Functions", lambda c: c in ["E0431", "E0432", "E0433", "E0434", "E0435", "E0436", "E0437", "E0464", "E0465"]),
        ("Sema: Ownership & Resources (Toka Specials)", lambda c: c in ["E0438", "E0439", "E0440", "E0441", "E0442", "E0443", "E0444", "E0458", "E0445", "E0451", "E0446", "E0466", "E0468", "E0447", "E0448", "E0449", "E0450", "E0467", "E0452", "E0453", "E0454", "E0455", "E0456", "E0457", "E0460", "E0461"]),
        ("Sema: Safety Redline Boundaries", lambda c: c in ["E0480", "E0481", "E0482"]),
        ("Sema: Memory Safety", lambda c: c in ["E0501", "E0502", "E0503"]),
        ("Pattern Matching", lambda c: c in ["E0550", "E0551", "E0552", "E0553", "E0554"]),
        ("Generics (Upcoming)", lambda c: c in ["E0601", "E0602", "E0603", "E0604", "E0607", "E0701", "E0702", "E0605", "E0606"]),
        ("Parser Errors", lambda c: c.startswith("E01")),
        ("Warnings", lambda c: c.startswith("W") or c.startswith("S")),
        ("System & CLI", lambda c: c.startswith("E09")),
    ]

    # Keep track of handled codes
    handled_codes = set()

    for category_name, rule in categories:
        category_entries = []
        for code, entry in diagnostics.items():
            if code not in handled_codes and rule(code):
                category_entries.append((code, entry))
                handled_codes.add(code)
        
        if category_entries:
            lines.append(f"// --- {category_name} ---")
            for code, entry in category_entries:
                diag_id = entry["id"]
                level = entry["level"]
                msg = entry["message"]
                
                # Format to look like original
                # DIAG(ID, Level, Code, Msg)
                # Align columns for readability
                id_part = f"{diag_id},"
                level_part = f"{level},"
                
                lines.append(f"DIAG({id_part:<28} {level_part:<8} \"{code}\", \"{msg}\")")
            lines.append("")

    # Catch-all for any other diagnostics not classified
    remaining_entries = []
    for code, entry in diagnostics.items():
        if code not in handled_codes:
            remaining_entries.append((code, entry))
            handled_codes.add(code)

    if remaining_entries:
        lines.append("// --- Miscellaneous ---")
        for code, entry in remaining_entries:
            diag_id = entry["id"]
            level = entry["level"]
            msg = entry["message"]
            lines.append(f"DIAG({diag_id}, {level}, \"{code}\", \"{msg}\")")
        lines.append("")

    # Write to .def file
    with open(def_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"Successfully generated {def_path} from {json_path}. Total entries: {len(diagnostics)}")

if __name__ == "__main__":
    main()
