import ansi::{Color, red, green, print_color}
import std/io::println

pub fn main() -> i32 {
    
    println("Toka Package Ecosystem Test")
    
    red("This string is printed in RED using pkg.tokalang.dev/zhyi/ansi!")
    green("All systems green. Package resolution works!")
    
    // Testing the inner Color structure
    auto c = Color::yellow()
    print_color(c, "- Yellow imported struct test.")
    
    return 0
}
