// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import std/io::println
import std/string::String
import core/types::LIMITS

shape Point (x :i32, y :i32)


fn main() -> i32 {
    // 1. Basic anonymous record
    auto r1 = (x = 100, y = 200)
    println("r1.x = {}", r1.x) 
    println("r1.y = {}", r1.y)
    assert(r1.x == 100, "r1.x mismatch")
    assert(r1.y == 200, "r1.y mismatch")

    // 2. Another one with same structure
    auto r2 = (
        x = 300, 
        y = 400,
        xy = ( 
            x = 10,
            y = 20
        )
    )
    println("r2.x = {}", r2.x)
    println("r2.xy.x = {}", r2.xy.x)
    assert(r2.x == 300, "r2.x mismatch")
    assert(r2.xy.x == 10, "r2.xy.x mismatch")
    
    println("LIMITS.u8.max = {}",LIMITS.u8.max)
    assert(LIMITS.u8.max == 255:u8, "LIMITS.u8.max mismatch")
    println("LIMITS.f32.min_positive = {}",LIMITS.f32.min_positive as f64)
    println("LIMITS.f32.epsilon = {}",LIMITS.f32.epsilon as f64)
    println("LIMITS.f32.bits.infinity = {}",LIMITS.f32.bits.infinity)
    println("LIMITS.f32.bits.nan = {}",LIMITS.f32.bits.nan)
    println("LIMITS.f32.bits.neg_zero = {}",LIMITS.f32.bits.neg_zero)
    
    // 3. Mixed types
    auto r3 = (name = "Toka", ver = 1)
    println("Lang: {}, Ver: {}", r3.name, r3.ver)

    // 4. Nested
    auto r4 = (top = (sub = 50))
    println("r4.top.sub = {}", r4.top.sub)

    // 5. Using named shape
    auto p1 = Point(x = 100, y = 200)
    println("p1.x = {}", p1.x)
    println("p1.y = {}", p1.y)

    // 6. Using LIMITS

    return 0
}
