import std/io::println
import std/task
import std/task::{block_on, __toka_spawn_blocking}

fn bar() -> async i32 {
    println("Inside bar")
    return 42
}

fn foo() -> async i32 {
    println("Before bar")
    // auto res = bar().await
    println("After bar")
    return 42
}

pub fn main() -> i32 {
    pure_caller()
    return 0
}

// 借用测试用例的特性消除悬挂限制
fn pure_caller() {
    block_on<i32>(foo())
}
