import std/io::{println}
import std/task::{sleep_async, block_on, __toka_spawn_blocking, current_time_ms}
import core/libc::{libc_exit}
import std/sys/libc::{libc_fflush, libc_printf}
import std/time::{SystemTime, Duration, DateTime}

fn log_ms(*msg: char) {
    auto ms = current_time_ms()
    auto sec = (ms / 1000:i64) as u64
    auto msec = ms % 1000:i64
    auto t = SystemTime(duration_since_epoch=Duration::from_secs(sec))
    auto dt = t.to_datetime()
    
    libc_printf("[%04d-%02d-%02d %02d:%02d:%02d.%03lld] %s\n" as *char, 
        dt.year, dt.month, dt.day, 
        dt.hour, dt.minute, dt.second, 
        msec, *msg)
    libc_fflush(0 as *void)
}

fn worker_a() -> async i32 {
    log_ms("[Worker A] OK!" as *char)
    sleep_async(50).await
    log_ms("[Worker A] FINISHED!" as *char)
    return 0
}

fn worker_b() -> async i32 {
    log_ms("[Worker B] OK!" as *char)
    sleep_async(10).await
    log_ms("[Worker B] FINISHED!" as *char)
    return 0
}

fn entry_point() -> async i32 {
    log_ms("[ENTRY] init" as *char)
    auto ta = worker_a().start
    auto tb = worker_b().start
    
    ta.await
    log_ms("[ENTRY] a.await done" as *char)
    
    tb.await
    log_ms("[ENTRY] b.await done" as *char)
    
    auto sl = sleep_async(300).start
    sl.await
    log_ms("[ENTRY] sleep done" as *char)
    return 0
}

pub fn main() -> i32 {
    log_ms("[MAIN] 1. call block_on" as *char)
    // block on completion
    auto handle = entry_point().start
    
    block_on<i32>(handle)
    log_ms("[MAIN] 2. block_on returned!" as *char)
    return 0
}
