import std/task::{sleep, block_on, __toka_spawn_blocking}
import std/io::{println}
import core/libc::{libc_exit}

// Used to demonstrate interruption of the second subtask
fn worker_b() -> async i32 {
    println(" --> [Worker B] Resumed and running background task!")
    return 0
}

fn worker_a() -> async i32 {
    println(" --> [Worker A] Resumed and running background task!")
    return 0
}

// Event loop sentinel task (specifically consumes coroutines accumulated in the queue)
fn event_loop_sentinel() -> async i32 {
    println("--- Queue Start Discharging ---")
    // Elegantly call the standard library's sleep method, avoiding direct exposure of libc
    sleep(100) 
    println("--- Queue Exhausted & Event Loop Shutdown ---")
    return 0
}

pub fn main() -> async i32 {
    println("1. [Async Main] I am an async coroutine!")
    println("2. [Async Main] Spawning background Workers to event queue...")
    
    // Enqueue two suspended background tasks
    worker_a().start
    worker_b().start
    
    println("3. [Async Main] Doing other heavy work synchronously before I yield...")
    
    // Force the current main coroutine to block, consuming WorkerA and WorkerB in the background queue.
    // This line is where the coroutine "out-of-order execution / dispatching" magic takes place.
    block_on<i32>(event_loop_sentinel())
    
    println("4. [Async Main] All done, shutting down the process safely.")
    libc_exit(0)
    return 0
}
