import std/io::{println}
import std/task::{sleep_async, block_on, __toka_spawn_blocking}
import core/libc::{libc_exit, libc_fflush, libc_printf}

fn worker_a() -> async i32 {
    println("[Worker A] OK!")
    libc_fflush(0 as *void)
    sleep_async(50).await
    println("[Worker A] FINISHED!")
    libc_fflush(0 as *void)
    return 0
}

fn worker_b() -> async i32 {
    println("[Worker B] OK!")
    libc_fflush(0 as *void)
    sleep_async(10).await
    println("[Worker B] FINISHED!")
    libc_fflush(0 as *void)
    return 0
}

fn entry_point() -> async i32 {
    println("[ENTRY] init")
    libc_fflush(0 as *void)
    auto ta = worker_a().start
    auto tb = worker_b().start
    
    ta.await
    println("[ENTRY] a.await done")
    libc_fflush(0 as *void)
    
    tb.await
    println("[ENTRY] b.await done")
    libc_fflush(0 as *void)
    
    auto sl = sleep_async(300).start
    sl.await
    println("[ENTRY] sleep done")
    libc_fflush(0 as *void)
    return 0
}

pub fn main() -> i32 {
    println("[MAIN] 1. call block_on")
    libc_fflush(0 as *void)
    // block on completion
    auto handle = entry_point().start
    
    block_on<i32>(handle)
    println("[MAIN] 2. block_on returned!")
    libc_fflush(0 as *void)
    return 0
}
