import std/task
import std/task::{block_on}
import sys/libc::{libc_usleep}
import std/io::{println}

fn secondary_task() -> async i32 {
    println("   [Task B] running now!")
    return 0
}

fn primary_task() -> async i32 {
    println("[Task A] Step 1")
    secondary_task().start
    println("[Task A] Task B has been spawned, but I am still running step 2...")
    return 0
}

fn supervisor() -> async i32 {
    primary_task().start
    // Force blocking for a while to prevent supervisor from ending too early and causing spawn_blocking to terminate
    // But here we use usleep(...) and then "wait" a little bit
    libc_usleep(100000)
    return 0
}

pub fn main() -> i32 {
    // But here spawn_blocking will exit directly once supervisor is finished.
    // We cannot guarantee the internal task is consumed. What can we do?
    supervisor().start
    // Directly consume all tasks in a loop until empty, or we write a simple block_on ourselves
    return 0
}
