import std/task::{sleep, block_on, __toka_spawn_blocking}
import std/io::{println}
import core/libc::{libc_exit}

// 用来演示第二个子任务的中断
fn worker_b() -> async i32 {
    println(" --> [Worker B] Resumed and running background task!")
    return 0
}

fn worker_a() -> async i32 {
    println(" --> [Worker A] Resumed and running background task!")
    return 0
}

// 调度器看守任务（专门消耗队列中刚才积压的协程）
fn event_loop_sentinel() -> async i32 {
    println("--- Queue Start Discharging ---")
    // 优雅调用标准库的 sleep 方法，避免直接暴露 libc
    sleep(100) 
    println("--- Queue Exhausted & Event Loop Shutdown ---")
    return 0
}

pub fn main() -> async i32 {
    println("1. [Async Main] I am an async coroutine!")
    println("2. [Async Main] Spawning background Workers to event queue...")
    
    // 入队两个挂起的后台任务
    worker_a().start
    worker_b().start
    
    println("3. [Async Main] Doing other heavy work synchronously before I yield...")
    
    // 强制当前主协程阻塞，消费所有背景队列里的 WorkerA 和 WorkerB。
    // 这行就是展现协程“乱序/分发”魔法的地方。
    block_on<i32>(event_loop_sentinel())
    
    println("4. [Async Main] All done, shutting down the process safely.")
    libc_exit(0)
    return 0
}
