import std/task
import std/task::{block_on}
import std/sys/libc::{libc_usleep}
import std/io::{println}

fn secondary_task() -> async i32 {
    println("   [Task B] running now!")
    return 0
}

fn primary_task() -> async i32 {
    println("[Task A] Step 1")
    secondary_task().start
    println("[Task A] Task B has been spawned, but I am still running step 2...")
    return 0
}

fn supervisor() -> async i32 {
    primary_task().start
    // 强制阻塞一会，防止 supervisor 太早结束导致 spawn_blocking 结束
    // 但是这里用 usleep(...) 然后再稍微“等待”一下
    libc_usleep(100000)
    return 0
}

pub fn main() -> i32 {
    // 但是这里 spawn_blocking 会在 supervisor 跑完后直接退出。
    // 我们没法保证内部 task 被消费。我们可以怎么做呢？
    supervisor().start
    // 直接循环消费所有任务直到为空，或者我们自己写个简单的 block_on
    return 0
}
