import std/io::{println}
import std/task::{sleep_async, block_on, __toka_spawn_blocking, current_time_ms}
import core/libc::{libc_exit}
import sys/libc::{libc_fflush, libc_printf}
import std/time::{SystemTime, Duration, DateTime}

fn log_ms(*msg: char) {
    auto ms = current_time_ms()
    auto sec = (ms / 1000:i64) as u64
    auto msec = ms % 1000:i64
    auto t = SystemTime(duration_since_epoch=Duration::from_secs(sec))
    auto dt = t.to_datetime()
    
    libc_printf(c"[%04d-%02d-%02d %02d:%02d:%02d.%03lld] %s\n", 
        dt.year, dt.month, dt.day, 
        dt.hour, dt.minute, dt.second, 
        msec, *msg)
    libc_fflush(0 as *void)
}

fn worker_a() -> async i32 {
    log_ms(c"[Worker A] OK!")
    sleep_async(50).await
    log_ms(c"[Worker A] FINISHED!")
    return 0
}

fn worker_b() -> async i32 {
    log_ms(c"[Worker B] OK!")
    sleep_async(10).await
    log_ms(c"[Worker B] FINISHED!")
    return 0
}

fn entry_point() -> async i32 {
    log_ms(c"[ENTRY] init")
    auto ta = worker_a().start
    auto tb = worker_b().start
    
    ta.await
    log_ms(c"[ENTRY] a.await done")
    
    tb.await
    log_ms(c"[ENTRY] b.await done")
    
    auto sl = sleep_async(300).start
    sl.await
    log_ms(c"[ENTRY] sleep done")
    return 0
}

pub fn main() -> i32 {
    log_ms(c"[MAIN] 1. call block_on")
    // block on completion
    auto handle = entry_point().start
    
    block_on<i32>(handle)
    log_ms(c"[MAIN] 2. block_on returned!")
    return 0
}
