import std/sync::{Mutex}
import std/thread::{thread_spawn, yield_now}
import std/io::{println}

shape Counter(
    val#: i32
)
impl Counter@encap {
    fn drop(self#) {
        println("Counter dropped")
    }
}
pub fn main() -> i32 {
    println("Testing atomic reference counting for ~Mutex...")
    {
        auto xxx = Mutex<Counter>::new(Counter(val=0))
    }
    auto ~m = Mutex<Counter>::make(Counter(val=0))
    
    auto ~m1 = ~m
    auto ~m2 = ~m
    auto ~m3 = ~m
    auto ~m4 = ~m
    auto ~m5 = ~m

    auto f1: fn() -> cede i32 = { [cede m1] =>
        auto i# = 0
        while i < 50000 {
            auto ~local = ~m1
            // Use locked value to ensure no optimization removes this
            auto g = local.lock().unwrap()
            auto *p# = g.get_ref()
            p.val = p.val + 1
            i = i + 1
        }
        return cede 0
    }

    auto f2: fn() -> cede i32 = { [cede m2] =>
        auto i# = 0
        while i < 50000 {
            auto ~local = ~m2
            auto g = local.lock().unwrap()
            auto *p# = g.get_ref()
            p.val = p.val + 1
            i = i + 1
        }
        return cede 0
    }

    auto f3: fn() -> cede i32 = { [cede m3] =>
        auto i# = 0
        while i < 50000 {
            auto ~local = ~m3
            auto g = local.lock().unwrap()
            auto *p# = g.get_ref()
            p.val = p.val + 1
            i = i + 1
        }
        return cede 0
    }

    auto f4: fn() -> cede i32 = { [cede m4] =>
        auto i# = 0
        while i < 50000 {
            auto ~local = ~m4
            auto g = local.lock().unwrap()
            auto *p# = g.get_ref()
            p.val = p.val + 1
            i = i + 1
        }
        return cede 0
    }

    auto f5: fn() -> cede i32 = { [cede m5] =>
        auto i# = 0
        while i < 50000 {
            auto ~local = ~m5
            auto g = local.lock().unwrap()
            auto *p# = g.get_ref()
            p.val = p.val + 1
            i = i + 1
        }
        return cede 0
    }

    println("Spawning 5 threads, each doing 50000 local clone/drops of ~Mutex...")

    auto t1# = thread_spawn<i32>(cede f1)
    auto t2# = thread_spawn<i32>(cede f2)
    auto t3# = thread_spawn<i32>(cede f3)
    auto t4# = thread_spawn<i32>(cede f4)
    auto t5# = thread_spawn<i32>(cede f5)

    auto r1 = t1#.join().unwrap()
    auto r2 = t2#.join().unwrap()
    auto r3 = t3#.join().unwrap()
    auto r4 = t4#.join().unwrap()
    auto r5 = t5#.join().unwrap()

    if r1 != 0 || r2 != 0 || r3 != 0 || r4 != 0 || r5 != 0 {
        println("A thread failed!")
        return 1
    }

    {
        auto g = m#.lock().unwrap()
        auto *val = g.get_ref()
        println("Final Mutex data: {}", val.val)
    }

    println("Stress test PASS! Reference counter didn't corrupt :)")
    return 0
}
