// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import std/io::println
import std/memory
import core/traits::{@encap}
// import std/release::assert // Now in prelude


shape Point(
    x:i32, 
    y:i32,
    &drop_flag#: i32
    )
impl Point@encap {
    pub *
    pub fn clone(self) = delete
    fn drop(self#) {
        println("    Dropping Point x:{} y:{}, drop_flag={}", self.x, self.y, self.drop_flag)
        self.drop_flag += 1
    }
}

shape Resource (
    id: i32,
    point: Point
    )

/*
impl Resource@encap {
    pub *
    pub fn clone(self) = delete
    fn drop(self#) {
        println("Dropping Resource {}", self.id)
    }
}
*/

fn main() -> i32 {
    println("Start")
    auto tmp_drop_flag# = 0
    {
        auto r1 = Resource(id=1,point=Point(x=1,y=1,&drop_flag = &tmp_drop_flag))
        println("Inside block")
        assert(tmp_drop_flag == 0, "tmp_drop_flag should be 0")
        println("reached end of block")
    }
    println("After block")
    assert(tmp_drop_flag == 1, "tmp_drop_flag should be 1")

    auto p1_drop_flag# = 0
    auto s1_drop_flag# = 0
    auto r2_drop_flag# = 0
    {
        auto ^#p1 = new Resource(id=11, point=Point(x=10,y=1,&drop_flag = &p1_drop_flag))
        println("p1_drop_flag: {}", p1_drop_flag)
        assert(p1_drop_flag == 0, "p1_drop_flag should be 0")

        auto ~s1 = new Resource(id=21, point=Point(x=20,y=1,&drop_flag = &s1_drop_flag))
        println("s1_drop_flag: {}", s1_drop_flag)
        assert(s1_drop_flag == 0, "s1_drop_flag should be 0")

        //auto ^p2 = ^p1
        println("will rebind ^#p1")
        tmp_drop_flag = 0
        ^#p1 = new Resource(id=31, point=Point(x=30,y=1,&drop_flag = &tmp_drop_flag))
        println("after rebind ^#p1")
        println("DEBUG: Before Assert")
        assert(p1_drop_flag == 1, "p1_drop_flag should be 1")
        println("DEBUG: After Assert")

        auto ~s2 = ~s1
        println("s2_drop_flag: {}", s1_drop_flag)

        auto r2 = Resource(id=41, point=Point(x=40,y=1,&drop_flag = &r2_drop_flag))
        println("reached end of block")
    }
    println("DEBUG: Block Ended")
    assert(p1_drop_flag == 1, "p1_drop_flag should be 1")
    assert(s1_drop_flag == 1, "s1_drop_flag should be 1")
    assert(r2_drop_flag == 1, "r2_drop_flag should be 1")
    assert(tmp_drop_flag == 1, "tmp_drop_flag should be 1")

    p1_drop_flag = 0
    s1_drop_flag = 0
    r2_drop_flag = 0
    tmp_drop_flag = 0
    {
        auto ~#p1 = new Resource(id=11, point=Point(x=10,y=1,&drop_flag = &p1_drop_flag))
        auto ~pp1 = ~p1
        assert(p1_drop_flag == 0, "p1_drop_flag should be 0")

        auto ~s1 = new Resource(id=21, point=Point(x=20,y=1,&drop_flag = &s1_drop_flag))
        println("s1_drop_flag: {}", s1_drop_flag)
        assert(s1_drop_flag == 0, "s1_drop_flag should be 0")

        //auto ~p2 = ~p1
        println("2 will rebind ~#p1")
        tmp_drop_flag = 0
        ~#p1 = new Resource(id=31, point=Point(x=30,y=1,&drop_flag = &tmp_drop_flag))
        println("2 after rebind ~#p1")
        assert(p1_drop_flag == 0, "p1_drop_flag should be 0 because old ~#p1 is shared (refcount > 0)")

        auto ~s2 = ~s1
        println("2 s2_drop_flag: {}", s1_drop_flag)
        
        auto r2 = Resource(id=41, point=Point(x=40,y=1,&drop_flag = &r2_drop_flag))
        println("2 reached end of block")
    }
    println("End of main")
    return 0
}
