import std/btree_map::{BTreeMap}
import core/option::{Maybe}
import core/primitives
import std/io

pub fn main() -> i32 {
    io::println("Starting...")
    auto map# = BTreeMap<i32, i32>::new()
    
    auto i# = 0
    while i < 5 {
        map#.insert(i, i * 10)
        i += 1
    }
    
    io::println("Inserted 5")
    
    map#.insert(0, 5000)
    io::println("Overwrite 0 done")
    
    return 0
}
