fn biger(a:i32, b:i32) -> &i32 <- a|b {
    if a > b {
        return &a
    } else {
        return &b
    }
}

fn swap_pos(a:i32, b:i32) -> res: (first: &i32, second: &i32)
effects:
    res.first <- b
    res.second <- a
{
    return (first = &b, second = &a)
}

shape RefLife(
    `&same_life: i32,
    &other_life: i32
)

fn main() -> i32 {
    auto a = -1
    auto b = 0
    auto &c = biger(a, b)
    auto res = swap_pos(a, b)
    auto d = RefLife(&same_life=&c, &other_life=res.&first)
    return c
}