import std/vec::Vec
import std/io::println

fn main() -> i32 {
    {
        auto v# = Vec<i32>::with_capacity(10)
        v#.push(10)
        v#.push(20)
        v#.push(30)

        println("Iterating Vec<T>:")
        for auto x in v {
            println("Item: {}", x)
        }

        for auto &x in v {//borrow 
            println("Item: {}", x)
        }
    }

    {
        auto v# = Vec<&i32>::with_capacity(10)
        auto a = 10
        v#.push(&a)
        v#.push(&a)
        v#.push(&a)

        println("Iterating Vec<&T>:")
        for auto &x in v {
            println("Item: {}", x)
            assert(x == 10,"x should be 10")
        }

        for auto &&x in v {//borrow 
            println("Item: {}", x)
            assert(x == 10,"x should be 10")
        }
    }


    
    return 0
}
