// targets/pass/complex_generic.tk
import core/traits::{@encap}
import std/io::println
// 1. Value Generics (-1 order)
shape Buffer<T, N_: usize>(
    data: [T; N_], // Use N_ as array length
    len: usize
)

// 2. Recursive Generics (0-th order) + Nested Usage
shape Node<T>(
    // Nested: Node contains a Buffer, size fixed to 5
    buf: Buffer<T, 5>, 
    
    // Recursive: points to the next node of the same type
    nul ^next: Node<T> 
)
impl<T> Node<T>@encap {
    pub buf
    pub fn clone(self) = delete
    fn drop(self#) {
        println("dropping Node")
    }
}
/*
trait MyDrop {
    fn mydrop(self#)
}
impl Node<i32>@MyDrop {
    fn mydrop(self#) {
        println("dropping Node")
    }
}
*/
fn main() -> i32 {
    // 3. Instantiation
    // This triggers a chain of monomorphizations:
    // Node<i32> -> Buffer<i32, 5> -> [i32; 5]
    
    auto ^head: Node<i32> = new Node<i32>(
        // Using array repeat initialization syntax [val; count], the compiler internally uses memset to efficiently implement array broadcast initialization
        // Here the compiler needs to recognize [0; 5] matching [i32; 5]
        buf = Buffer<i32, 5>(data=[0,1,2,3,4], len=5), 
        
        ^next = null
    )
    for auto i in [0,1,2,3,4] {
        println("head.buf.data[{}] = {}", i, head.buf.data[i])
        assert(head.buf.data[i] == i,"check head.val[{}]")
    }
    //head.mydrop()
    return 0
}