import std/io::println
import std/map::{HashMap}
import core/option::{Option}

fn main() -> i32 {
    auto map# = HashMap<i32, i32>::new()
    
    // Insert
    map#.insert(1, 100)
    map#.insert(2, 200)
    map#.insert(3, 300)
    
    // Verify Get
    if map.get(1).unwrap() != 100 { return 101 }
    if map.get(2).unwrap() != 200 { return 102 }
    if map.get(3).unwrap() != 300 { return 103 }
    
    // Verify Iterator
    auto iter# = map#.iter()
    auto count# = 0
    auto sum_k# = 0
    auto sum_v# = 0
    
    while true {
        auto res = iter#.next()
        match res {
            auto MapResult<i32,i32>::Some(entry) => {
                count += 1
                sum_k += entry.key
                sum_v += entry.val
            }
            auto MapResult<i32,i32>::None => {
                break
            }
        }
    }
    
    if count != 3 {
         println("Count mismatch") 
         return 201 
    }
    if sum_k != 6 { return 202 } // 1+2+3
    if sum_v != 600 { return 203 } // 100+200+300
    
    // Cleanup Check (Use After Free/Double Free implicitly tested by destructor)
    println("HashMap Test Passed")
    return 0
}
