import std/io::{File, println, remove_file}
import std/string::{String}

fn main() -> i32 {
    auto path = String::from("test_raii_output.txt")
    
    // Scope 1: Write
    {
        auto f# = File::open(path, String::from("w"))
        f.write(String::from("Hello RAII\n"))
        // f drops here, should close
    }
    
    // Scope 2: Read
    {
        auto f# = File::open(path, String::from("r"))
        // read_line returns IoResult
        auto tmp# = f.read_line()
        auto s = tmp#.unwrap()
        println("Read back: {}", s.c_str())
        if s.eq(String::from("Hello RAII\n")) {
             println("Content matches!")
        } else {
             // panic("Content mismatch")
             return 1
        }
        // f drops here, should close
    }
    
    remove_file(path)
    return 0
}
