import std/io::println
import ./nested/toka-ink as toka-ink

fn main() -> i32 {
    // 1. Test namespace function call
    auto res = toka-ink::render(42)
    println("res = {}", res)

    // 2. Test anonymous record with kebab-case key
    auto deps = (toka-ink = "1.0.0")

    // 3. Test space-less subtraction
    auto sub1 = 10-3
    auto sub2 = sub1-2
    println("sub2 = {}", sub2)

    return 0
}
