// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import std/io::println

fn main() -> i32 {
    auto i# = 0
    loop i < 5 {
        println("while: {}", i)
        i += 1
        if i == 3 { 
            println("i = {}, break", i)
            break 
        }
        if i == 2 { 
            println("i = {}, continue", i)
            continue 
        }
    }

    // Range loop
    i = 0
    for auto x in [0,1,2] {
        if i == 0 {
            assert(x == 0, "x mismatch")
        }
        if i == 1 {
            assert(x == 1, "x mismatch")
        }
        if i == 2 {
            assert(x == 2, "x mismatch")
        }
        println("for range: {}", x)
        i += 1
    }

    // Loop
    i = 0
    loop {
        if i > 10 { 
            println("i = {}, break", i)
            break 
        }
        i += 1
    }

    // Loop with condition
    auto j# = 0
    loop j < 10 {
        if j == 5 {
            println("j = {}, break", j)
            break
        }
        j += 1
    }
    return 0
}
