// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import std/io::println
import std/memory

fn main() -> i32 {
    for auto x in [10,20,30] {
        println("x={}", x)
        match x {
            10 => {println("Matched 10")}
            20 => {println("Matched 20")}
            _ => {println("Wildcard")}
        }
    }

    for auto x in [40,50,80,100] {
        match x {
            50 => {println("No match")}
            auto v if v > 80 => {println("Matched variable x={} > 80", v)}
            auto v => {println("Matched variable v={}", v)}
            _ => {println("Wildcard")}
        }
    }

    auto y = for auto x in [1,2] {
        pass match x {
            1 => {pass 1}
            2 => {pass 2}
            _ => {pass 0}
        }
    }
    or {
        pass -1
    }
    println("y={}", y)
    assert(y == 1, "y mismatch")

    println("End")
    return 0
}
