import std/io::println
import std/memory
import core/traits::{@encap}


shape Point(
    x: i32 = 0,
    y#: i32
)
shape Node(
    val: i32,
    nul ^point: Point
    pp: Point?
)
impl Node@encap {
    fn drop(self#) {
        println("drop Node")
    }
    pub fn clone(self) -> Node {
        // Dummy clone
        return Node(val=0, ^point=nullptr, pp=none)
    }
}

fn main() -> i32 {
    {
        // Path 1: Success path
        auto n_ok = Node(val=1, ^point=new Point(x=2, y=3), pp=Point(x=4, y=5))
        auto v1 = n_ok.??point.x
        println("Success access: {}", v1) // Should print 2
        assert(v1 == 2, "Success access failed")

        auto v2 = n_ok.pp??.x 
        println("Success access: {}", v2) // Should print 4
        assert(v2 == 4, "Success access failed") 

        n_ok.pp??.y = 111
        println("Success access: {}", n_ok.pp??.y) // Should print 111
        assert(n_ok.pp??.y == 111, "Success access failed")
    }
    //* Path 2: Panic path    
    auto n_null = Node(val=1, ^point=nullptr, pp=none)
    println("This should panic next...pointer is nullptr")
    auto v2 = n_null.??point.x // EXPECT_PANIC

    println("This should panic next...soul is none")
    auto v3 = n_null.pp??.x // noEXPECT_PANIC
    //*/
    
    return 0
}
