
import std/io::{println}
import std/net::{TcpListener, TcpStream}
import core/libc
import core/types
import std/string::{String}

extern fn sleep(seconds: i32) -> i32
extern fn fork() -> i32

fn run_server(port: i32) {
    unsafe {
        println("[Server] Starting on port {}...", port)
        auto listener = TcpListener::bind(String::from("127.0.0.1"), port)
        if !listener.is_valid() {
            println("[Server] Bind failed")
            libc::libc_exit(1)
        }

        println("[Server] Listening...")
        auto stream = listener.accept()
        if !stream.is_valid() {
             println("[Server] Accept failed")
             libc::libc_exit(1)
        }
        println("[Server] Accepted connection")
        
        auto buf: [char; 128] = [0 as char; 128]
        // echo loop
        auto *buf_ptr# = &buf[0] as *u8
        while true {
             auto n = stream.read(buf_ptr, 128)
             if n <= 0 {
                 break
             }
             stream.write(buf_ptr, n as usize)
        }
        println("[Server] Done")
    }
}

fn main() -> i32 {
    unsafe {
        auto pid = fork()
        if pid == 0 {
             run_server(9092) 
             libc::libc_exit(0)
        }
        
        sleep(1)
        println("[Client] Connecting...")
        auto stream = TcpStream::connect(String::from("127.0.0.1"), 9092)
        
        if !stream.is_valid() {
             println("[Client] Connect failed")
             return 1
        }
        println("[Client] Connected!")
        
        auto msg = String::from("Hello")
        stream.write_string(msg)
        
        auto buf: [char; 128] = [0 as char; 128]
        auto *buf_ptr# = &buf[0] as *u8
        auto n = stream.read(buf_ptr, 128)
        println("[Client] Received: {}", n)
        
        return 0
    }
}
