import std/io::println
import std/memory

shape Point(
    x: i32,
    y: i32
)
shape Node(
    val: i32,
    pp: Point?
)

fn main() -> i32 {
    // 1. Test successful wrap and unwrap
    auto n = Node(val=1, pp=Point(x=10, y=20))
    auto v = n.pp??.x
    println("Success access: {}", v) // Should be 10
    
    // 2. Test none assignment and panic
    auto n2 = Node(val=2, pp=none)
    println("This should panic next...")
    //auto v2 = n2.pp??.x 
    
    return 0
}
