// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import std/io::println

shape Data (
    v: i32
)

fn main() -> i32 {
    auto nul ^p = new Data(v = 42)
    
    // Narrowing: nul ^p is ^p
    guard ^p {
        println("Success: p.v = {}", p.v)
        assert(p.v == 42, "p.v value mismatch")
    } else {
        println("Failure: p is null\n")
        assert(false, "p is null (Logic should not reach here)")
    }

    auto nul ^q:Data = null
    guard ^q {
        println("Error: q should be null\n")
        assert(false, "q is not null (Logic should not reach here)")
    } else {
        println("Success: q confirmed null\n")
        assert(true, "q confirmed null logic executed")
    }

    return 0
}
