
import std/io::println

shape MyObj(
    id: i32,
    name: string
)

impl MyObj {
    pub fn eq(self, other: MyObj) -> bool {
        return self.id == other.id && self.name == other.name 
    }
}

fn main() -> i32 {
    auto s1 = string::from("hello")
    auto s2 = string::from("hello")
    auto s3 = string::from("world")
    
    // Test std::string overload
    if s1 == s2 {
        if s1 != s3 {
            println("{}", "string overload ok!")
        } else {
            return 1
        }
    } else {
        return 1
    }
    
    // Test Custom Object overload
    auto obj1 = MyObj(id=10, name=string::from("dpai"))
    auto obj2 = MyObj(id=10, name=string::from("dpai"))
    auto obj3 = MyObj(id=20, name=string::from("dpai"))
    
    if obj1 == obj2 {
        if obj1 != obj3 {
            println("{}", "Custom Object overload ok!")
            return 0
        }
    }
    
    return 1
}
