// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import std/io::println

shape Data (v: i32)

fn main() -> i32 {
    // Parsing check for Logical Operators
    auto t = true
    auto f = false
    auto res = t && f || t

    if res {
        println("Logical ops work: result is true\n")
    }

    // Checking Parser Update for Attributes
    auto ^#p1 = new Data(v=10)
    println("Rebindable pointer p1->v: {}", p1.v)

    {
        // Nullable Pointer
        auto nul ^p2 = new Data(v=99)

        // New syntax: 'is' operator for nullptr check. 
        guard ^p2 {
            println("Nullable pointer is not nullptr (is check)\n")
            println("p2->v: {}", p2.v)
        }
    }
    {
        // Nullable Pointer
        auto nul ^p3:Data = nullptr

        // New syntax: 'is' operator for nullptr check. 
        guard ^p3 {
            println("Nullable pointer is not nullptr (is check)\n")
        }
        else
        {
            println("Nullable pointer is nullptr (is check)\n")
        }
    }
    return 0
}
