import std/path

import std/io::{println}

fn main() -> i32 {
    // 1. Test join
    auto joined = path::join(string::from("/usr/local"), string::from("bin/toka"))
    println("Joined: {}", joined)
    if !joined.replace(92:char, 47:char).eq(string::from("/usr/local/bin/toka")) { return 1 }
    
    auto joined2 = path::join(string::from("/usr/"), string::from("bin/toka"))
    println("Joined2: {}", joined2)
    if !joined2.replace(92:char, 47:char).eq(string::from("/usr/bin/toka")) { return 2 }
    
    // 2. Test extension
    auto ext = path::extension(string::from("/usr/local/bin/toka"))
    println("Ext: {}", ext)
    if !ext.eq(string::from("")) { return 3 }
    
    auto ext2 = path::extension(string::from("test.tk"))
    println("Ext2: {}", ext2)
    if !ext2.eq(string::from("tk")) { return 4 }
    
    // 3. Test basename
    auto base = path::basename(string::from("/usr/local/bin/toka"))
    println("Basename: {}", base)
    if !base.eq(string::from("toka")) { return 5 }
    
    // 4. Test dirname
    auto dir = path::dirname(string::from("/usr/local/bin/toka"))
    println("Dirname: {}", dir)
    if !dir.eq(string::from("/usr/local/bin")) { return 6 }
    
    auto dir2 = path::dirname(string::from("/toka"))
    println("Dirname2: {}", dir2)
    if !dir2.eq(string::from("/")) { return 7 }
    
    auto dir3 = path::dirname(string::from("toka"))
    println("Dirname3: {}", dir3)
    if !dir3.eq(string::from(".")) { return 8 }

    println("Path test passed!")
    return 0
}
