// tests/pass/rebind_no_sigil.tk
// EXPECT: Parsing tests/pass/rebind_no_sigil.tk...
// EXPECT: Parse Successful. Running Semantic Analysis...
// EXPECT: Sema Successful. Merging and Generating IR...

pub fn __toka_free(nul *#ptr: i32) {
    unsafe {
        if *ptr != null {
            *ptr = null
        }
    }
}

pub fn main() -> i32 {
    auto nul *#p: i32 = null
    __toka_free(*#p)
    return 0
}
