// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import std/io::println

shape Data (
    val: i32
)

impl Data@encap {
    fn drop(self#) {
        println("Dropping Data, val={}", self.val)
    }
}

fn check_unique_ptr(nul ^ptr: Data) {
    guard ^ptr {
        println("Unique pointer is not nullptr confirmed, ptr.val={}", ptr.val)
        assert(ptr.val == 10, "Unique pointer is not nullptr confirmed")
    } else {
        println("Unique pointer is nullptr confirmed")
        assert(false, "Unique pointer is nullptr confirmed")
    }
}

fn check_shared_ptr(nul ~ptr: Data) {
    guard ~ptr {
        println("Shared pointer is not nullptr confirmed, ptr.val={}", ptr.val)
        assert(ptr.val == 20, "Shared pointer is not nullptr confirmed")
    } else {
        println("Shared pointer is nullptr confirmed")
        assert(false, "Shared  pointer is nullptr confirmed")
    }
}

fn check_raw_ptr(nul *ptr: Data) {
    guard *ptr {
        println("Raw pointer is not nullptr confirmed")
    } else {
        println("Raw pointer is nullptr confirmed")
        assert(false, "Raw  pointer is nullptr confirmed")
    }
}



fn main() -> i32 {
    auto nul *q# = unsafe alloc [2]Data(val = 999)
    println("--- Before check_raw_ptr ---")
    check_raw_ptr(*q)
    println("--- Before unsafe free ---")
    guard *q
    {
        unsafe {
            assert(q[0].val == 999, "q#[0].val mismatch")
            assert(q[1].val == 999, "q#[1].val mismatch")
            
            q[0].val = 100
            assert(q[0].val == 100, "q#[0].val mismatch")
            
            q[1].val = 200            
            assert(q[1].val == 200, "q#[1].val mismatch")
        }
    }


    guard *q {
        unsafe free [2]*q
        println("--- After unsafe free ---")
    }    

    auto nul ~r = new Data(val = 20)
    check_shared_ptr(~r)
    auto nul ~rr = ~r
    check_shared_ptr(~rr)


    auto nul ^p = new Data(val = 10)
    check_unique_ptr(^p)
    guard ^p {
        println("Unique pointer is not nullptr confirmed, ptr.val={}", p.val)
        assert(p.val == 10, "Unique pointer is not nullptr confirmed")
    } else {
        println("Unique pointer is nullptr confirmed")
        assert(false, "Unique  pointer is nullptr confirmed")
    }
    auto nul ^pp = ^p
    check_unique_ptr(^pp)


    auto nul ~r = new Data(val = 20)
    check_shared_ptr(~r)

    return 0
}
