// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import std/io::println

fn test_relay(x: i32) -> i32 {
    return for auto i in [1] {
        pass match x {
            10 => { pass 100 }
            _  => { pass 200 }
        }
    } or {
        pass -1
    }
}

fn main() -> i32 {
    auto r1 = test_relay(10)
    println("r1={}", r1)
    assert(r1 == 100, "r1 mismatch")

    auto r2 = test_relay(20)
    println("r2={}", r2)
    assert(r2 == 200, "r2 mismatch")

    println("Return relay test passed")
    return 0
}
