// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import std/io::println

fn main() -> i32 {
    auto x# = 10
    {
        auto &y# = &x
        y = 20
        println("y = {}", y)
    }
    // y is dead. x should be free.
    assert(x == 20, "x should be 20")
    x = 30
    println("x = {}", x)
    assert(x == 30, "x should be 30")


    auto y# = 10
    {
        auto &#z# = &x
        z = 33
        println("z = {}", z)

        &z = &y
        z = 44
        println("z = {}", z)
    }
    println("x = {}, y = {}", x, y)
    assert(x == 33, "x should be 33")
    assert(y == 44, "y should be 44")

    // z is dead. y should be free.
    y = 30
    assert(y == 30, "y should be 30")
    return 0
}
