// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// simple_string.tk
import std/io::println
import std/string::String

fn main() -> i32 {
    auto s = String::from("Hi")
    println("{}", s.len())
    println("{}", s.capacity())
    println("{}", s.c_str())
    // Address-of method call (implicit passing of pointer to self?)
    // String::push_str takes self#. 
    s#.push_str(" World")
    
    // println uses copy or we should implement borrow?
    // s is value. 
    println("Original: {}", s.c_str()) 
    
    // Copy construction test
    // String has pointer.
    
    // s.clone()? No clone yet.
    // s2 = s => Shallow copy.
    // s2#.push_str("!") => realloc self.buf (same buf).
    // s.buf is now dangling.
    // So we must NOT use s and s2 together without copy semantics.
    // Testing mutation on s directly.
    
    s#.push_str("!")
    println("Appended: {}", s.c_str())

    assert(s.len() == 9, "s.len mismatch")

    s#.clear()
    println("Clear: len:{}, capacity:{}", s.len(), s.capacity())
    assert(s.len() == 0, "s.len mismatch")
    //assert(s.capacity() == 13, "s.capacity mismatch")
    return 0
}
