// tests/pass/std_test.tk
import std/io::println
import core/option::{Option}
import core/result::{Result}
import std/vec::{Vec}
import std/fs

import std/fs::{ReadDir}

fn test_option() {
    auto some = Option<i32>::Some(10)
    auto no_val = Option<i32>::None
}

fn test_result() {
    auto ok = Result<i32, string>::Ok(100)
    auto err = Result<i32, string>::Err(string::from("error"))
}

fn test_vec() {
    auto v# = Vec<i32>::new()
    v#.push(1)
    v#.push(2)
    
    auto val = v#.pop().unwrap() // pop moves v
    println("Pop: {}", val)
    
    auto val2 = v.get(0) // get moves v
    println("Get: {}", val2)
}

fn test_fs() {
    auto path = string::from(".")
    auto dir = fs::read_dir(path)
}

fn main() -> i32 {
    println("--- Testing Std ---")
    test_option()
    test_result()
    test_vec()
    test_fs()
    println("--- Passed ---")
    return 0
}
