// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import std/string
import std/io::{println, File}

fn main() -> i32 {
    auto content = String::from("Hello File IO!\nLine 2")
    
    // Write
    auto f1# = File::open(String::from("test_io.txt"), String::from("w"))
    f1.write(content)
    f1#.close()
    
    // Read
    auto f2# = File::open(String::from("test_io.txt"), String::from("r"))
    
    println("Reading lines:")
    
    // Line 1
    auto tmp1# = f2.read_line()
    auto l1 = tmp1#.unwrap()
    println("Line 1: {}", l1.c_str())
    if !l1.eq(String::from("Hello File IO!\n")) {
         println("Line 1 mismatch")
         return 1
    }

    // Line 2
    auto tmp2# = f2.read_line()
    auto l2 = tmp2#.unwrap()
    println("Line 2: {}", l2.c_str())
     if !l2.eq(String::from("Line 2")) {
         println("Line 2 mismatch")
         // Note: "Line 2" might not have \n if file ended there. 
         // My write call content was "Hello File IO!\nLine 2".
         return 1
    }
    
    // EOF Check - read_line OK("")
    auto tmp3# = f2.read_line()
    auto l3 = tmp3#.unwrap()
    if l3.len() != 0 {
        println("Expected EOF/Empty, got len {}", l3.len())
        return 1
    }
    
    f2#.close()
    
    println("IO Line Test Passed")
    return 0
}
