import std/io::{println}
import std/string::{String}
import stdx/json::{serialize_shape, to_json_string, @ToJson}

shape Address(
    city: str,
    zip: i32
)

impl Address@ToJson {
    pub fn write_json(self, buf#: String) -> String {
        buf = serialize_shape(self, buf)
        return buf
    }
}

shape User(
    name: str,
    id: i32,
    active: bool,
    payment: f64,
    addr: Address
)

impl User@ToJson {
    pub fn write_json(self, buf#: String) -> String {
        buf = serialize_shape(self, buf)
        return buf
    }
}

pub fn main() -> i32 {
    unsafe {
        auto a = Address(city="Neo Tokyo", zip=9900)
        auto u = User(name="Alice", id=42, active=true, payment=99.9, addr=a)
        
        auto json_text = to_json_string(u)
        println("Output text len: {}", json_text.len())
        println("Output: {}", json_text.c_str())
        
        return 0
    }
}
