import std/sync::{Mutex, Once}
import std/thread::{thread_spawn, yield_now}
import std/io::{println}

shape SharedData(
    counter: i32
)

pub fn main() -> i32 {
    auto init_val = SharedData(counter = 0)
    auto state# = Mutex<SharedData>::new(init_val)
    auto once# = Once::new()
    
    auto init_fn: fn() = { =>
        auto lock = state#.lock().unwrap()
        auto *val# = lock.get_ref()
        val.counter = val.counter + 1
        println("init_fn executed!")
    }
    
    auto task: fn() -> cede i32 = { =>
        once#.call(init_fn)
        return cede 0
    }
    
    auto t1# = thread_spawn<i32>(task)
    auto t2# = thread_spawn<i32>(task)
    auto t3# = thread_spawn<i32>(task)
    
    t1#.join().unwrap()
    t2#.join().unwrap()
    t3#.join().unwrap()
    
    auto lock = state#.lock().unwrap()
    auto *val = lock.get_ref()
    println("Once counter value: {}", val.counter)
    assert(val.counter == 1, "Expected counter to be 1")
    
    println("Once test passed!")
    return 0
}
