import std/mpsc::{channel, Sender, Receiver}
import std/vec::{Vec}
import std/thread::{thread_spawn, JoinHandle}
import std/io::{println}

fn main() -> i32 {
    auto pair# = channel<i32>()
    // Test basic send and recv
    auto msg_to_send = 42:i32
    pair.tx#.send(cede msg_to_send)
    auto res_opt = pair.rx#.recv()
    
    auto msg_opt = res_opt.unwrap()
    auto msg = msg_opt.unwrap()
    println("Received: {}", msg)
    assert(msg == 42, "msg must be 42")
    
    return 0
}
