import std/io::{println}
import std/thread::{thread_spawn, JoinHandle}
import std/mpsc::{sync_channel, Sender, Receiver}

pub fn main() -> i32 {
    auto pair# = sync_channel<i32>(2)
    auto tx2# = pair.tx#.clone()
    
    // Fill up the channel
    pair.tx#.send(cede 1:i32).unwrap()
    pair.tx#.send(cede 2:i32).unwrap()
    
    // cede pair completely into the closure
    auto f: fn() -> cede i32 = { [cede pair#] => 
        auto val1 = pair.rx#.recv().unwrap()
        auto val2 = pair.rx#.recv().unwrap()
        auto val3 = pair.rx#.recv().unwrap()
        return cede 0
    }
    auto t# = thread_spawn<i32>(cede f)
    
    // Now send the 3rd item, this should block until the receiver pops
    tx2#.send(cede 3:i32).unwrap()
    
    // Wait for the receiver to finish
    auto res = t#.join().unwrap()
    println("Bounded channel sync test passed!")
    return 0
}
