import stdx/encoding/base64::{encode_str}
import std/io::{println}
import std/string::{string}

pub fn main() -> i32 {
    auto t1 = string::from("light work.")
    auto res1 = encode_str(t1.as_view())
    println("light work. -> {}", res1.as_view())
    assert(res1.eq(string::from("bGlnaHQgd29yay4=")), "Failed Base64 light work.")

    auto t2 = string::from("light work")
    auto res2 = encode_str(t2.as_view())
    println("light work -> {}", res2.as_view())
    assert(res2.eq(string::from("bGlnaHQgd29yaw==")), "Failed Base64 light work")

    auto t3 = string::from("light wor")
    auto res3 = encode_str(t3.as_view())
    println("light wor -> {}", res3.as_view())
    assert(res3.eq(string::from("bGlnaHQgd29y")), "Failed Base64 light wor")

    println("All Base64 tests passed!")
    return 0
}
