import core/types::{usize, Addr}
import core/traits::*
import core/primitives

pub shape BTreeNode<'K, 'V> (
    keys#: ['K; 5],
    vals#: ['V; 5],
    children#: [Addr; 6],
    len#: usize = 0,
    is_leaf#: bool = true
)

pub fn btree_node_new<'K: @PartialOrd, 'V>() -> Addr {
    unsafe {
        return (unsafe alloc [1] BTreeNode<'K, 'V>) as Addr
    }
}

pub fn main() -> i32 {
    auto addr = btree_node_new<i32, i32>()
    return 0
}
