import std/crypto/sha1::{Sha1}
import std/encoding/base64::{encode_bytes}
import std/io::{println}
import std/string::{String}

pub fn main() -> i32 {
    // Standard WebSocket example handshake test
    auto origin = String::from("dGhlIHNhbXBsZSBub25jZQ==258EAFA5-E914-47DA-95CA-C5AB0DC85B11")
    
    auto sha1# = Sha1::new()
    sha1#.update(origin.as_view())
    auto hash_res = sha1#.finalize()
    
    auto b64_res = encode_bytes(&hash_res as *[u8], 20)
    
    println("WS Hash: {}", b64_res.c_str())
    assert(b64_res.eq(String::from("s3pPLMBiTxaQ9kYGzzhZRbK+xOo=")), "Failed SHA-1 + B64 WS sequence!")

    println("All SHA1 tests passed!")
    return 0
}
