import std/net::{Ipv4Addr, resolve_ipv4}
import std/string::{String}
import core/result::{Okay}
import std/io::{println}

pub fn main() -> i32 {
    // 1. Resolve localhost
    auto local_res = resolve_ipv4(String::from("localhost"))
    match local_res {
        auto Okay::Err(&e) => {
            println("resolve localhost failed")
            return 1
        }
        auto Okay::Ok(&ip) => {
            // Should be 127.0.0.x
            if ip.octets[0] != 127:u8 {
                println("localhost is not 127.x.x.x")
                println("oct0: {}, oct1: {}, oct2: {}, oct3: {}", ip.octets[0] as i32, ip.octets[1] as i32, ip.octets[2] as i32, ip.octets[3] as i32)
                return 1
            }
        }
    }
    
    // 2. Resolve IP string (getaddrinfo handles this too)
    auto ip_res = resolve_ipv4(String::from("8.8.8.8"))
    match ip_res {
        auto Okay::Err(&e) => {
            println("resolve 8.8.8.8 failed")
            return 1
        }
        auto Okay::Ok(&ip) => {
            if ip.octets[0] != 8:u8 || ip.octets[1] != 8:u8 || ip.octets[2] != 8:u8 || ip.octets[3] != 8:u8 {
                println("8.8.8.8 resolved incorrectly")
                return 1
            }
        }
    }
    
    return 0
}
