import std/io::println
import std/thread::{spawn, sleep_ms}
import std/string::{String}

pub fn main() -> i32 {
    auto target = 256:i64

    auto f:fn() -> cede String = { [cede target] =>
        sleep_ms(1000:u32)
        auto text# = String::from("Toka Threading with generics: target = ")
        auto num_s = String::from_i64(target)
        text#.push_str(num_s.c_str())
        println("Thread 1 OK")
        return cede text
    }
    
    // Spawn a thread and explicitly capture `target` by moving it (cede) into the thread!
    auto handle# = spawn<String>(f)

    //println("target = {}", target) //error: use of moved value: `target`

    auto handle2# = spawn<String>({ =>
        auto text = String::from("Hello from background thread!")
        println("Thread 2 OK")
        return cede text
    })
    
    println("Main thread is waiting...")
    
    auto j1 = handle#.join()
    auto res1 = j1.unwrap()
    auto j2 = handle2#.join()
    auto res2 = j2.unwrap()
    
    println("Thread 1 returned: {}", res1.c_str())
    println("Thread 2 returned: {}", res2.c_str())
    println("Thread finished! Memory will safely drop. Shutting down.")
    
    return 0
}
