// Copyright (c) 2025 YiZhonghua<zhyi@dpai.com>. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import std/string
import std/io::println

fn main() -> i32 {
    auto s1 = string::from_int(12345)
    println("int: {}", s1.c_str())
    if s1.len() != 5 { return 1 }
    
    auto s2 = string::from_i64(9223372036854775807)
    println("i64: {}", s2.c_str())
    
    auto s3 = string::from_f64(3.141592)
    println("f64: {}", s3.c_str())
    
    return 0
}
