import std/io::println
shape U (
    as Int: i32
    | as Float: f32
)

fn main() -> i32 {
    println("--- Test 1: Named Constructor ---")
    // 1. 初始化满尺寸成员 (4 bytes) -> 合法
    auto u# = U(Int = 42) 
    println("u.Int = {}", u.Int)

    assert(u.Int == 42, "u.Int init mismatch")

    println("--- Test 2: Bitcast View ---")
    // 2. 写入 Float
    u.Float = 3.14:f32
    // 3.14f 的位模式是 0x4048F5C3 (1078523331)
    
    // 读取 Int 视图
    auto i = u.Int
    println("u.Int (from Float) = {}", i)
    assert(i == 1078523331, "Float to Int bitcast error. Expected 1078523331")

    println("Skipping Test 3 (Partial Byte Update banned)")

    println("SUCCESS")
    return 0
}