import std/io::println

shape TStruct<T>(val: T)

impl<T> TStruct<T> @encap {
    pub fn clone(self) = delete
    fn drop(self#) {
        println("drop TStruct")
    }
}

impl<T> TStruct<T> {
    fn method(self) {
        println("method called")
    }
}

fn main() -> i32 {
    {
        auto x# = TStruct(val=10)
        x.method()
        x#.drop() // Explicit call to verify existence
    }
    println("after scope")
    return 0
}
